SELECT * FROM ALL_USERS;
--계정 생성
CREATE USER TEST01 IDENTIFIED BY TEST01;
--계정에 권한 부여
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO TEST01;
GRANT RESOURCE, CONNECT TO TEST01;
--테이블 스페이스 지정
ALTER USER TEST01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
--계정삭제
DROP USER TEST01;
--비밀번호 변경
ALTER USER TEST01 IDENTIFIED BY 바꿀비밀번호;