--테이블의 기본적 조회
select * from employees;
--SQL문은 대소문자를 구분하지 않습니다.
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID FROM EMPLOYEES;
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL FROM EMPLOYEES;
--컬럼을 조회하는 위치에서 * / + - 연산이 가능합니다.
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,SALARY+SALARY*0.1 FROM EMPLOYEES;
--NULL값 확인
SELECT COMMISSION_PCT,MANAGER_ID FROM EMPLOYEES;
--컬럼 엘리어스
SELECT EMPLOYEE_ID AS 아이디,FIRST_NAME AS 이름,LAST_NAME AS 성,SALARY,SALARY+SALARY*0.1 AS 보너스 FROM EMPLOYEES;
--||연결자
SELECT FIRST_NAME||' '||LAST_NAME FROM EMPLOYEES;
SELECT FIRST_NAME || ' ' || LAST_NAME || '''S SALARY IS $' || SALARY AS 급여 FROM EMPLOYEES;
--DISTINCT (중복 행 제거)
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DEPARTMENT_ID FROM EMPLOYEES;
--ROWNUM,ROWID(로우넘은 쿼리 결과에 대한 행번호)
SELECT ROWNUM,ROWID,EMPLOYEE_ID,FIRST_NAME||LAST_NAME FROM EMPLOYEES;
SELECT ROWNUM,EMAIL FROM EMPLOYEES;
--WHERE 절 [BETWEEN, IN]
SELECT FIRST_NAME,LAST_NAME,EMAIL,JOB_ID FROM EMPLOYEES WHERE JOB_ID='IT_PROG';
SELECT * FROM EMPLOYEES WHERE LAST_NAME='King';
SELECT * FROM EMPLOYEES WHERE HIRE_DATE='04/01/30';--날짜
SELECT * FROM EMPLOYEES WHERE SALARY>=15000;--숫자
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=90;
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 15000 AND 30000;
SELECT * FROM EMPLOYEES WHERE SALARY>=15000 AND SALARY<=30000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '03/01/01' AND '03/12/31';--날짜
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN(30,60,90);
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IN(101,102,103,104,105);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN('IT_PROG','AC_MGR');
--LIKE검색 (%는 모든, _은 한글자 위치를 찾아낼 때)
SELECT FIRST_NAME || ' ' || LAST_NAME AS 이름, HIRE_DATE AS 입사일 FROM EMPLOYEES WHERE HIRE_DATE LIKE '03%';--03년 입사
SELECT FIRST_NAME || ' ' || LAST_NAME AS 이름, HIRE_DATE AS 입사일 FROM EMPLOYEES WHERE HIRE_DATE LIKE '%15';--15일 입사
SELECT FIRST_NAME || ' ' || LAST_NAME AS 이름, HIRE_DATE AS 입사일 FROM EMPLOYEES WHERE HIRE_DATE LIKE '%05%';--05가 있다면 다 찾음
SELECT FIRST_NAME || ' ' || LAST_NAME AS 이름, HIRE_DATE AS 입사일 FROM EMPLOYEES WHERE HIRE_DATE LIKE '___05%';--05월 입사
SELECT FIRST_NAME,EMAIL FROM EMPLOYEES WHERE EMAIL LIKE '%A%';
SELECT FIRST_NAME,EMAIL FROM EMPLOYEES WHERE EMAIL LIKE '__A%';
--NULL검사 IS NULL, IS NOT NULL
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;
--AND, OR (AND가 우선순위가 빠릅니다)
SELECT * FROM EMPLOYEES WHERE JOB_ID='IT_PROG' AND SALARY>=7000;
SELECT * FROM EMPLOYEES WHERE JOB_ID='IT_PROG' OR SALARY>=7000;
SELECT * FROM EMPLOYEES WHERE JOB_ID='IT_PROG' OR JOB_ID='FI_MGR' AND SALARY>=7000;
SELECT * FROM EMPLOYEES WHERE (JOB_ID='IT_PROG' OR JOB_ID='FI_MGR') AND SALARY>=7000;--소괄호 우선순위
--데이터 정렬(SELECT 구문의 마지막)
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE;
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE DESC;
SELECT * FROM EMPLOYEES WHERE JOB_ID IN('IT_PROG','SA_REP')ORDER BY FIRST_NAME ASC;
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 10000 ORDER BY EMPLOYEE_ID DESC;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL ORDER BY FIRST_NAME ASC;
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE ASC,FIRST_NAME DESC;--입사일 기준 오름차순, 그 안에서 이름 기준 내림차순
SELECT SALARY+SALARY*COMMISSION_PCT AS 급여 FROM EMPLOYEES ORDER BY 급여 ASC;