SELECT RPAD(SUBSTR(FIRST_NAME,1,3),LENGTH(FIRST_NAME),'*') AS name,LPAD(SALARY,10,'*') AS salary FROM EMPLOYEES WHERE LOWER(JOB_ID)='it_prog';
SELECT FIRST_NAME||' '||LAST_NAME AS 이름,REPLACE(HIRE_DATE,'/','') AS 입사일자 FROM EMPLOYEES ORDER BY FIRST_NAME ASC;
SELECT CONCAT('02',LTRIM(PHONE_NUMBER,SUBSTR(PHONE_NUMBER,1,3))) AS 전화_번호 FROM EMPLOYEES;
SELECT RPAD(SUBSTR(FIRST_NAME,1,3),LENGTH(FIRST_NAME),'*') AS name,LPAD(SALARY,10,'*') AS salary FROM EMPLOYEES WHERE LOWER(JOB_ID)='it_prog';