--1번
SELECT *
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;--106

SELECT *
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;--107

SELECT *
FROM EMPLOYEES E
RIGHT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;--122

SELECT *
FROM EMPLOYEES E
FULL OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;--123

--2번
SELECT FIRST_NAME||' '||LAST_NAME AS 이름, E.DEPARTMENT_ID
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE EMPLOYEE_ID=200;

--3번
SELECT FIRST_NAME||' '||LAST_NAME AS 이름,E.JOB_ID AS 직무_아이디,JOB_TITLE AS 직무_타이틀
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID=J.JOB_ID
ORDER BY FIRST_NAME ASC;

--4번
SELECT *
FROM JOBS J
LEFT OUTER JOIN JOB_HISTORY H
ON J.JOB_ID=H.JOB_ID;

--5번
SELECT FIRST_NAME||' '||LAST_NAME AS 이름,DEPARTMENT_NAME AS 부서명
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE FIRST_NAME='Steven' AND LAST_NAME='King';

--6번
SELECT *
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

--7번
SELECT EMPLOYEE_ID AS 사원번호,
        FIRST_NAME||' '||LAST_NAME AS 이름,
        SALARY AS 급여,
        DEPARTMENT_NAME AS 부서명,
        LOCATION_ID AS 근무지
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE JOB_ID='SA_MAN';

--8번
SELECT *
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID=J.JOB_ID
WHERE JOB_TITLE='Stock Manager' OR JOB_TITLE='Stock Clerk';

--9번
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IS NULL;

--10번
SELECT A.FIRST_NAME||' '||A.LAST_NAME AS 사원_이름,
        B.FIRST_NAME||' '||B.LAST_NAME AS 메니저_이름
FROM EMPLOYEES A
LEFT OUTER JOIN EMPLOYEES B
ON A.MANAGER_ID=B.EMPLOYEE_ID;

--11번
SELECT A.MANAGER_ID AS 메니저,
        B.FIRST_NAME||' '||B.LAST_NAME AS 메니저_이름,
        B.SALARY
FROM EMPLOYEES A
LEFT OUTER JOIN EMPLOYEES B
ON A.MANAGER_ID=B.EMPLOYEE_ID
WHERE A.MANAGER_ID IS NOT NULL
ORDER BY B.SALARY DESC;