INSERT INTO DEPTS VALUES (280,'개발',NULL,1800);
INSERT INTO DEPTS VALUES (290,'회계부',NULL,1800);
INSERT INTO DEPTS VALUES (300,'재정',301,1800);
INSERT INTO DEPTS VALUES (310,'인사',302,1800);
INSERT INTO DEPTS VALUES (320,'영업',303,1700);
DELETE FROM DEPTS WHERE DEPARTMENT_ID>200;
SELECT * FROM DEPTS;
ROLLBACK;
UPDATE DEPTS SET MANAGER_ID=100 WHERE MANAGER_ID IS NOT NULL;
SELECT * FROM DEPTS;
SELECT * FROM DEPARTMENTS;
MERGE INTO DEPTS A
USING DEPARTMENTS B
ON (A.DEPARTMENT_ID=B.DEPARTMENT_ID)
WHEN MATCHED THEN
UPDATE SET 
A.DEPARTMENT_NAME=B.DEPARTMENT_NAME,
A.MANAGER_ID=B.MANAGER_ID,
A.LOCATION_ID=B.LOCATION_ID
WHEN NOT MATCHED THEN
INSERT VALUES
(B.DEPARTMENT_ID,B.DEPARTMENT_NAME,B.MANAGER_ID,B.LOCATION_ID);
SELECT * FROM DEPTS;
MERGE INTO DEPTS A
USING (SELECT * FROM DEPARTMENTS) B
ON (A.DEPARTMENT_ID=B.DEPARTMENT_ID)
WHEN MATCHED THEN
UPDATE SET 
A.DEPARTMENT_NAME=B.DEPARTMENT_NAME,
A.MANAGER_ID=B.MANAGER_ID,
A.LOCATION_ID=B.LOCATION_ID
WHEN NOT MATCHED THEN
INSERT VALUES
(B.DEPARTMENT_ID,B.DEPARTMENT_NAME,B.MANAGER_ID,B.LOCATION_ID);
SELECT * FROM DEPTS;