CREATE SEQUENCE SNSBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE SNSBOARD(
    BNO NUMBER(10,0) DEFAULT SNSBOARD_SEQ.NEXTVAL NOT NULL CONSTRAINT SNSBOARD_PK PRIMARY KEY,
    WRITER VARCHAR2(50) DEFAULT 'DEFAULT_WRITER' NOT NULL,
    CONTENT VARCHAR2(2000) DEFAULT 'DEFAULT_CONTENT' NOT NULL,
    FILELOCA VARCHAR2(200) DEFAULT 'DEFAULT_FILELOCA' NOT NULL,--파일이 저장된 위치
    FILENAME VARCHAR2(200) DEFAULT 'DEFAULT_FILENAME' NOT NULL,--파일 이름
    FILEREALNAME VARCHAR2(200) DEFAULT 'DEFAULT_FILEREALNAME' NOT NULL,--파일 실제 이름
    REGDATE DATE DEFAULT SYSDATE NOT NULL
);