CREATE TABLE MOVIE(
    MOVIE_CODE VARCHAR2(30) DEFAULT 'DEFAULT_MOVIE_CODE' NOT NULL CONSTRAINT MOVIE_PK PRIMARY KEY,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    MOVIE_TITLE VARCHAR2(30) DEFAULT 'DEFAULT_MOVIE_TITLE' NOT NULL,
    MOVIE_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_MOVIE_CONTENT' NOT NULL,
    MOVIE_IMAGE VARCHAR2(3000) DEFAULT 'DEFAULT_MOVIE_IMAGE' NOT NULL,
    MOVIE_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    MOVIE_HIT NUMBER(10,0) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE MOVIE_REPLY_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE MOVIE_REPLY(
    MOVIE_REPLY_NUMBER NUMBER(10,0) DEFAULT MOVIE_REPLY_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT MOVIE_REPLY_PK PRIMARY KEY,
    MOVIE_CODE VARCHAR2(30) DEFAULT 'DEFAULT_MOVIE_CODE' NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    MOVIE_REPLY_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_MOVIE_REPLY_CONTENT' NOT NULL,
    MOVIE_REPLY_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE POPCORN(
    POPCORN_CODE VARCHAR2(30) DEFAULT 'DEFAULT_POPCORN_CODE' NOT NULL CONSTRAINT POPCORN_PK PRIMARY KEY,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    POPCORN_TITLE VARCHAR2(30) DEFAULT 'DEFAULT_POPCORN_TITLE' NOT NULL,
    POPCORN_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_POPCORN_CONTENT' NOT NULL,
    POPCORN_IMAGE VARCHAR2(3000) DEFAULT 'DEFAULT_POPCORN_IMAGE' NOT NULL,
    POPCORN_PRICE NUMBER(10,0) DEFAULT 1000 NOT NULL,
    POPCORN_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    POPCORN_HIT NUMBER(10,0) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE POPCORN_REPLY_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE POPCORN_REPLY(
    POPCORN_REPLY_NUMBER NUMBER(10,0) DEFAULT POPCORN_REPLY_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT POPCORN_REPLY_PK PRIMARY KEY,
    POPCORN_CODE VARCHAR2(30) DEFAULT 'DEFAULT_POPCORN_CODE' NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    POPCORN_REPLY_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_POPCORN_REPLY_CONTENT' NOT NULL,
    POPCORN_REPLY_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE REVIEW_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE REVIEW(
    REVIEW_NUMBER NUMBER(10,0) DEFAULT REVIEW_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT REVIEW_PK PRIMARY KEY,
    MOVIE_CODE VARCHAR2(30) DEFAULT 'DEFAULT_MOVIE_CODE' NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    REVIEW_TITLE VARCHAR2(30) DEFAULT 'DEFAULT_REVIEW_TITLE' NOT NULL,
    REVIEW_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_REVIEW_CONTENT' NOT NULL,
    REVIEW_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    REVIEW_HIT NUMBER(10,0) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE REVIEW_REPLY_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE REVIEW_REPLY(
    REVIEW_REPLY_NUMBER NUMBER(10,0) DEFAULT REVIEW_REPLY_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT REVIEW_REPLY_PK PRIMARY KEY,
    REVIEW_NUMBER NUMBER(10,0) DEFAULT 0 NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    REVIEW_REPLY_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_REVIEW_REPLY_CONTENT' NOT NULL,
    REVIEW_REPLY_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE NOTICE_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE NOTICE(
    NOTICE_NUMBER NUMBER(10,0) DEFAULT NOTICE_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT NOTICE_PK PRIMARY KEY,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    NOTICE_TITLE VARCHAR2(30) DEFAULT 'DEFAULT_NOTICE_TITLE' NOT NULL,
    NOTICE_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_NOTICE_CONTENT' NOT NULL,
    NOTICE_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    NOTICE_HIT NUMBER(10,0) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE NOTICE_REPLY_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE NOTICE_REPLY(
    NOTICE_REPLY_NUMBER NUMBER(10,0) DEFAULT  NOTICE_REPLY_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT NOTICE_REPLY_PK PRIMARY KEY,
    NOTICE_NUMBER NUMBER(10,0) DEFAULT 0 NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    NOTICE_REPLY_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_NOTICE_REPLY_CONTENT' NOT NULL,
    NOTICE_REPLY_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE QNA_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE QNA(
    QNA_NUMBER NUMBER(10,0) DEFAULT QNA_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT QNA_PK PRIMARY KEY,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    QNA_TITLE VARCHAR2(30) DEFAULT 'DEFAULT_QNA_TITLE' NOT NULL,
    QNA_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_QNA_CONTENT' NOT NULL,
    QNA_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    QNA_HIT NUMBER(10,0) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE QNA_REPLY_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE QNA_REPLY(
    QNA_REPLY_NUMBER NUMBER(10,0) DEFAULT  QNA_REPLY_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT QNA_REPLY_PK PRIMARY KEY,
    QNA_NUMBER NUMBER(10,0) DEFAULT 0 NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    QNA_REPLY_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_QNA_REPLY_CONTENT' NOT NULL,
    QNA_REPLY_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE FOUND_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE FOUND(
    FOUND_NUMBER NUMBER(10,0) DEFAULT FOUND_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT FOUND_PK PRIMARY KEY,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    FOUND_TITLE VARCHAR2(30) DEFAULT 'DEFAULT_FOUND_TITLE' NOT NULL,
    FOUND_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_FOUND_CONTENT' NOT NULL,
    FOUND_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    FOUND_HIT NUMBER(10,0) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE FOUND_REPLY_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE FOUND_REPLY(
    FOUND_REPLY_NUMBER NUMBER(10,0) DEFAULT  FOUND_REPLY_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT FOUND_REPLY_PK PRIMARY KEY,
    FOUND_NUMBER NUMBER(10,0) DEFAULT 0 NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    FOUND_REPLY_CONTENT VARCHAR2(3000) DEFAULT 'DEFAULT_FOUND_REPLY_CONTENT' NOT NULL,
    FOUND_REPLY_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE CINEMA(
    CINEMA_CODE VARCHAR2(30) DEFAULT 'DEFAULT_CINEMA_CODE' NOT NULL CONSTRAINT CINEMA_PK PRIMARY KEY,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    CINEMA_LOCATION VARCHAR2(30) DEFAULT 'DEFAULT_CINEMA_LOCATION' NOT NULL,
    CINEMA_NAME VARCHAR2(30) DEFAULT 'DEFAULT_CINEMA_NAME' NOT NULL,
    CINEMA_INFORMATION VARCHAR2(3000) DEFAULT 'DEFAULT_CINEMA_INFORMATION' NOT NULL,
    CINEMA_IMAGE VARCHAR2(3000) DEFAULT 'DEFAULT_CINEMA_IMAGE' NOT NULL,
    CINEMA_MAXHOLE NUMBER(10,0) DEFAULT 0 NOT NULL,
    CINEMA_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE TIMETABLE_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE TIMETABLE(
    TIMETABLE_NUMBER NUMBER(10,0) DEFAULT TIMETABLE_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT TIMETABLE_PK PRIMARY KEY,
    CINEMA_CODE VARCHAR2(30) DEFAULT 'DEFAULT_CINEMA_CODE' NOT NULL,
    MOVIE_CODE VARCHAR2(30) DEFAULT 'DEFAULT_MOVIE_CODE' NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    TIMETABLE_HOLE NUMBER(10,0) DEFAULT 0 NOT NULL,
    TIMETABLE_TOTALSEAT NUMBER(10,0) DEFAULT 0 NOT NULL,
    TIMETABLE_START DATE DEFAULT SYSDATE NOT NULL,
    TIMETABLE_END DATE DEFAULT SYSDATE NOT NULL,
    TIMETABLE_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE RESERVATION_SEQUENCE INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE RESERVATION(
    RESERVATION_NUMBER NUMBER(10,0) DEFAULT RESERVATION_SEQUENCE.NEXTVAL NOT NULL CONSTRAINT RESERVATION_PK PRIMARY KEY,
    TIMETABLE_NUMBER NUMBER(10,0) DEFAULT 0 NOT NULL,
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL,
    RESERVATION_ROW VARCHAR2(30) DEFAULT 'A' NOT NULL,
    RESERVATION_SEAT VARCHAR2(30) DEFAULT '1' NOT NULL,
    RESERVATION_REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE MEMBERS(
    MEMBERS_ID VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ID' NOT NULL CONSTRAINT MEMBERS_PK PRIMARY KEY,
    MEMBERS_PW VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_PW' NOT NULL,
    MEMBERS_NAME VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_NAME' NOT NULL,
    MEMBERS_NICKNAME VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_NICKNAME' NOT NULL,
    MEMBERS_PHONE VARCHAR2(30) DEFAULT '01099999999' NOT NULL,
    MEMBERS_EMAIL VARCHAR2(30) DEFAULT 'MEM@CINEMA.COM' NOT NULL,
    MEMBERS_ADDRESS_NUMBER VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ADDRESS_NUMBER' NOT NULL,
    MEMBERS_ADDRESS_BASIC VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ADDRESS_BASIC' NOT NULL,
    MEMBERS_ADDRESS_DETAIL VARCHAR2(30) DEFAULT 'DEFAULT_MEMBERS_ADDRESS_DETAIL' NOT NULL,
    MEMBERS_GRADE VARCHAR2(30) DEFAULT 'NORMAL' NOT NULL,
    MEMBERS_VIP VARCHAR2(30) DEFAULT 'NORMAL' NOT NULL,
    MEMBERS_STATUS VARCHAR2(30) DEFAULT 'NORMAL' NOT NULL,
    MEMBERS_MONEY NUMBER(10,0) DEFAULT 0 NOT NULL,
    MEMBERS_POINT NUMBER(10,0) DEFAULT 0 NOT NULL,
    MEMBERS_INFORMATION VARCHAR2(3000) DEFAULT 'DEFAULT_MEMBERS_INFORMATION' NOT NULL,
    MEMBERS_IMAGE VARCHAR2(3000) DEFAULT 'DEFAULT_MEMBERS_IMAGE' NOT NULL,
    MEMBERS_REGDATE DATE DEFAULT SYSDATE NOT NULL
);