CREATE TABLE MEMBERS(
    ID VARCHAR2(30) NOT NULL,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30),
    PHONE1 VARCHAR2(30),
    PHONE2 VARCHAR2(30),
    PHONE3 VARCHAR2(30),
    GENDER VARCHAR2(1)
);
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK PRIMARY KEY (ID);