CREATE TABLE USERS(
    USERID VARCHAR2(50) DEFAULT '아이디' NOT NULL,
    USERPW VARCHAR2(50) DEFAULT '비밀번호' NOT NULL,
    USERNAME VARCHAR2(50) DEFAULT '이름' NOT NULL,
    USERPHONE1 VARCHAR2(50) DEFAULT '폰넘버1' NOT NULL,
    USERPHONE2 VARCHAR2(50) DEFAULT '폰범버2' NOT NULL,
    USEREMAIL1 VARCHAR2(50) DEFAULT '이메일1' NOT NULL,
    USEREMAIL2 VARCHAR2(50) DEFAULT '이메일2' NOT NULL,
    ADDRZIPNUM VARCHAR2(50) DEFAULT '압축' NOT NULL,
    ADDRBASIC VARCHAR2(300) DEFAULT '베이직' NOT NULL,
    ADDRDETAIL VARCHAR2(300) DEFAULT '디테일' NOT NULL,
    REGDATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE USERS ADD CONSTRAINT USERS_OK PRIMARY KEY (USERID);