SELECT * FROM MEMBER01;
CREATE TABLE BOARD01(
    NUM NUMBER(10,0) CONSTRAINT BOARD01_PK PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(200)
);
CREATE SEQUENCE BOARD01_SEQ;
INSERT INTO BOARD01 VALUES(BOARD01_SEQ.NEXTVAL,'TEST','TEST'||BOARD01_SEQ.CURRVAL,'TEST'||BOARD01_SEQ.CURRVAL);
SELECT * FROM BOARD01;
COMMIT;
SELECT *
FROM(SELECT ROWNUM AS RN,
            NUM,
            ID,
            TITLE,
            CONTENT
    FROM(SELECT NUM,
                ID,
                TITLE,
                CONTENT
        FROM BOARD01
        ORDER BY NUM DESC
    )
)
WHERE RN>10 AND RN<=20;
UPDATE BOARD01 SET ID='aaa123';
COMMIT;
SELECT * FROM MEMBER01 M
JOIN(
SELECT *
FROM(SELECT ROWNUM AS RN,
            NUM,
            ID,
            TITLE,
            CONTENT
    FROM(SELECT NUM,
                ID,
                TITLE,
                CONTENT
        FROM BOARD01
        ORDER BY NUM DESC
    )
)
WHERE RN>10 AND RN<=20) B
ON M.ID=B.ID;
SELECT M.ID,
        M.PW,
        M.EMAIL,
        M.ADDRESS,
        B.NUM,
        B.TITLE,
        B.CONTENT
FROM MEMBER01 M
JOIN BOARD01 B
ON M.ID=B.ID;
SELECT M.ID,
        M.PW,
        M.EMAIL,
        M.ADDRESS,
        B.NUM,
        B.TITLE,
        B.CONTENT
FROM MEMBER01 M
JOIN BOARD01 B
ON M.ID='aaa123';