--테이블의 기본적 조회
select * from employees;
--SQL문은 대소문자를 구분하지 않습니다.
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID FROM EMPLOYEES;
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL FROM EMPLOYEES;
--컬럼을 조회하는 위치에서 * / + - 연산이 가능합니다.
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,SALARY+SALARY*0.1 FROM EMPLOYEES;
--NULL값 확인
SELECT COMMISSION_PCT,MANAGER_ID FROM EMPLOYEES;
--컬럼 엘리어스
SELECT EMPLOYEE_ID AS 아이디,FIRST_NAME AS 이름,LAST_NAME AS 성,SALARY,SALARY+SALARY*0.1 AS 보너스 FROM EMPLOYEES;
--||연결자
SELECT FIRST_NAME||' '||LAST_NAME FROM EMPLOYEES;