CREATE SEQUENCE COMP_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE COMPLAIN(
    REGDATE DATE DEFAULT SYSDATE NOT NULL,
    SECTOR VARCHAR2(50) DEFAULT '대분류' NOT NULL,
    COMPTYPE VARCHAR2(50) DEFAULT '소분류' NOT NULL,
    ADID VARCHAR2(50) DEFAULT 'ADMIN' NOT NULL,
    ADNAME VARCHAR2(50) DEFAULT '홍길동' NOT NULL,
    CUSNAME VARCHAR2(50) DEFAULT '정연주' NOT NULL,
    CUSMAIL VARCHAR2(50) DEFAULT 'yj070517@naver.com' NOT NULL,
    CUSADD VARCHAR2(50) DEFAULT '010-5575-5589' NOT NULL,
    TITLE VARCHAR2(50) DEFAULT '민원제목' NOT NULL,
    COMPCON VARCHAR2(1000) DEFAULT '민원내용' NOT NULL,
    ANS VARCHAR2(1000) DEFAULT '민원답변' NOT NULL,
    ANSDATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(50) DEFAULT '전달' NOT NULL,
    MEMO VARCHAR2(1000) DEFAULT '메모' NOT NULL,
    IMGFILE VARCHAR2(1000) DEFAULT '이미지파일' NOT NULL,
    NFILE VARCHAR2(1000) DEFAULT '첨부파일' NOT NULL,
    COMPMARK VARCHAR2(50) DEFAULT '화이트' NOT NULL,
    COMPNUM NUMBER(10,0) DEFAULT COMP_SEQ.NEXTVAL NOT NULL
);
ALTER TABLE COMPLAIN ADD CONSTRAINT COMP_PK PRIMARY KEY (COMPNUM);
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
INSERT INTO COMPLAIN(TITLE) VALUES('테스트');
COMMIT;