--그룹함수 AVG,MAX,MIN,SUM,COUNT
SELECT AVG(SALARY), MAX(SALARY), MIN(SALARY), SUM(SALARY), COUNT(SALARY) FROM EMPLOYEES;
SELECT AVG(SALARY), MAX(SALARY), MIN(SALARY), SUM(SALARY), COUNT(*) FROM EMPLOYEES;
SELECT COUNT(*) FROM EMPLOYEES; --총 행 데이터의 수
SELECT COUNT(FIRST_NAME) FROM EMPLOYEES; --NULL이 아닌 FIRST_NAME 행의 수
SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES; --NULL이 아닌 COMMISSION_PCT 행의 수
SELECT COUNT(MANAGER_ID) FROM EMPLOYEES; --NULL이 아닌 MANAGER_ID 행의 수
--부서별로 그룹화, 그룹함수의 사용
SELECT DEPARTMENT_ID,AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
--그룹함수는 일반 컬럼과 동시에 출력할 수 없습니다.
SELECT DEPARTMENT_ID,AVG(SALARY) FROM EMPLOYEES;
--GROUP BY절을 사용할 때 GROUP절에 묶이지 않으면 다른 컬럼을 조회할 수 없습니다.
SELECT JOB_ID,DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
--GROUP BY절 2개 이상 사용
SELECT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID,JOB_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID,JOB_ID ORDER BY DEPARTMENT_ID;
--COUNT(*) OVER() 구문에서 예외적으로 컬럼에, 총 행의 수를 붙여서 확인이 가능합니다.
SELECT DEPARTMENT_ID,FIRST_NAME,LAST_NAME,JOB_ID,COUNT(*) OVER() FROM EMPLOYEES;
--GROUP BY 절의 조건 HAVING절
SELECT DEPARTMENT_ID,SUM(SALARY) 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY)>100000;
SELECT JOB_ID,COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING COUNT(*)>=20;
--부서 아이디가 50이상인 것들을 그룹화 시키고, 그룹평균중 5000이상만 조회
SELECT DEPARTMENT_ID,AVG(SALARY) AS 평균
FROM EMPLOYEES
WHERE DEPARTMENT_ID>=50
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>=5000;