--숫자함수 ROUND(올림), TRUNC(절삭)
SELECT 45.123 FROM DUAL;
SELECT ROUND(45.123,1),
       ROUND(45.123),
       ROUND(45.123,0),
       ROUND(45.123,-1)
FROM DUAL;
SELECT TRUNC(45.123,1),
       TRUNC(45.123),
       TRUNC(45.123,0),
       TRUNC(45.123,-1)
FROM DUAL;
SELECT CEIL(34.1) FROM DUAL;--올림
SELECT FLOOR(34.9) FROM DUAL;--내림
--날짜 함수 SYSDATE,SYSTIMESTAMP
SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
--날짜도 연산이 가능합니다
SELECT SYSDATE-27 FROM DUAL;
SELECT SYSDATE-HIRE_DATE FROM EMPLOYEES;--일수
SELECT FIRST_NAME,HIRE_DATE,(SYSDATE-HIRE_DATE)/7 FROM EMPLOYEES;--주
SELECT FIRST_NAME,HIRE_DATE,(SYSDATE-HIRE_DATE)/365 FROM EMPLOYEES;--년
--ROUND, TRUNC 날짜에 적용
SELECT ROUND(SYSDATE) FROM DUAL;
SELECT ROUND(SYSDATE,'YEAR') FROM DUAL;--년 기준으로 반올림
SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;--월 기준으로 반올림
SELECT ROUND(SYSDATE,'DAY') FROM DUAL;--일 기준으로 반올림(해당 주의 일요일 날짜 기준)
SELECT TRUNC(SYSDATE) FROM DUAL;
SELECT TRUNC(SYSDATE,'YEAR') FROM DUAL; --년 기준으로 절삭
SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL; --월 기준으로 절삭
SELECT TRUNC(SYSDATE,'DAY') FROM DUAL; --일 기준으로 절삭(해당 주의 일요일 날짜 기준)