--시퀀스(순차적으로 증가하는 값)
SELECT * FROM USER_SEQUENCES;
--시퀸스 생성
CREATE SEQUENCE DEPT2_SEQ;--자동생성
CREATE SEQUENCE DEPT2_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 10
    NOCYCLE
    NOCACHE;
--시퀸스 삭제
DROP SEQUENCE DEPT2_SEQ;
--시퀸스 사용(NEXTVAL,CURRVAL)
CREATE TABLE DEPT2(
    DEPT_NO NUMBER(2,0) CONSTRAINT DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(14),
    LOCA VARCHAR2(13),
    DEPT_DATE DATE
);
--시퀀스 값이 MAXVALUE에 도달하면 에러를 발생시킴
INSERT INTO DEPT2(DEPT_NO,DEPT_NAME,LOCA,DEPT_DATE) VALUES(DEPT2_SEQ.NEXTVAL,'TEST','TEST',SYSDATE);
SELECT * FROM DEPT2;
--시퀸스의 현재값 확인
SELECT DEPT2_SEQ.CURRVAL FROM DUAL;
--시퀸스 수정
ALTER SEQUENCE DEPT2_SEQ MAXVALUE 9999;--최대값 9999로 변경
ALTER SEQUENCE DEPT2_SEQ INCREMENT BY 100;--증가값이 100단위
--시퀸스 값을 다시 처음으로 돌리는 방법
SELECT DEPT2_SEQ.CURRVAL FROM DUAL;--현재시퀸스값 확인
ALTER SEQUENCE DEPT2_SEQ INCREMENT BY -110;--증가값을 변경
SELECT DEPT2_SEQ.NEXTVAL FROM DUAL;--다음시퀸스값 처리
ALTER SEQUENCE DEPT2_SEQ INCREMENT BY 1;
SELECT DEPT2_SEQ.CURRVAL FROM DUAL;
--PK를 값을 20200506-시퀸스값
--1. DEPT3_SEQ생성
--2. PK를 VARCHAR2로 선언
--3. INSERT시에 TO_CHAR()||시퀸스
CREATE SEQUENCE DEPT3_SEQ;
DROP SEQUENCE DEPT2_SEQ;
CREATE TABLE DEPT3(
    DEPT_NO VARCHAR2(30) CONSTRAINT DEPT3_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)
);
DROP TABLE DEPT2;
INSERT INTO DEPT3 VALUES(TO_CHAR(SYSDATE,'YYYYMMDD')||'-'||DEPT3_SEQ.NEXTVAL,'AAA');
SELECT * FROM DEPT3;