--문제1
CREATE TABLE MEMBERS(
    M_NAME VARCHAR2(3) NOT NULL,
    M_NUM NUMBER(1,0) CONSTRAINT MEM_MUMNUM_PK PRIMARY KEY,
    REG_DATE DATE NOT NULL CONSTRAINT MEM_REGDATE_UK UNIQUE,
    GENDER VARCHAR2(1) CONSTRAINT MEM_GENDER_CK CHECK (GENDER IN ('F','M')),
    LOCA NUMBER(4,0) CONSTRAINT MEM_LOCA_LOC_LOCID_FK REFERENCES LOCATIONS(LOCATION_ID)
);
INSERT INTO MEMBERS VALUES ('AAA',1,'2018/07/01','M',1800);
INSERT INTO MEMBERS VALUES ('BBB',2,'2018/07/02','F',1900);
INSERT INTO MEMBERS VALUES ('CCC',3,'2018/07/03','M',2000);
INSERT INTO MEMBERS VALUES ('DDD',4,SYSDATE,'M',2000);
--문제2
SELECT M_NAME,M_NUM,STREET_ADDRESS,LOCATION_ID
FROM MEMBERS M
INNER JOIN LOCATIONS L
ON M.LOCA=L.LOCATION_ID
ORDER BY M_NUM ASC;