CREATE TABLE DEPT2(
    DEPT_NO NUMBER(2,0),--자리수(10자리,소수점자리)자리수
    DEPT_NAME VARCHAR2(14),--14BYTE
    LOCA VARCHAR2(13),
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10,0)-- 자리수
);
DESC DEPT2;
INSERT INTO DEPT2 VALUES(99,'영업','서울',SYSDATE,2000000000);
SELECT * FROM DEPT2;
--열추가 (ADD)
ALTER TABLE DEPT2 ADD(DEPT_COUNT NUMBER(3,0));
DESC DEPT2;
--열이름 수정 (RENAME COLUMN)
ALTER TABLE DEPT2 RENAME COLUMN DEPT_COUNT TO EMP_COUNT;
DESC DEPT2;
--열 수정 (MODIFY)
ALTER TABLE DEPT2 MODIFY (EMP_COUNT NUMBER(4));
DESC DEPT2;
--열 삭제(DROP COLUMN)
ALTER TABLE DEPT2 DROP COLUMN DEPT_COUNT;
DESC DEPT2;
--테이블 삭제
DROP TABLE DEPT2;
--DROP TABLE DEPT2 CASCADE COSTRAINTS 제약조건명;
--테이블 생성과 제약 조건--
--테이블 열레벨 제약 조건(NOT NULL, UNIQUE, PK, FK, CHECK)
--NOT NULL : NULL을 허용하지 않는다
--UNIQUE : 중복 데이터가 들어오는 것을 방지
--PK : 테이블의 고유식별 컬럼
--FK : 참조 테이블의 PK를 저장하는 컬럼
--CHECK : 정의된 형식만 들어오도록 허용
CREATE TABLE DEPT2(
    DEPT_NO NUMBER(2,0) CONSTRAINT DEPT2_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR(14) NOT NULL,
    LOCA NUMBER(4,0) CONSTRAINT DEPT2_LOCA_LOC_LOCID_FK REFERENCES LOCATIONS(LOCATION_ID),
    DEPT_DATE DATE CONSTRAINT DEPT2_DEPTDATE_UK UNIQUE,
    DEPT_BONUS NUMBER(10,0),
    DEPT_GENDER VARCHAR2(1) CONSTRAINT DEPT2_DEPTGENDER_CK CHECK (DEPT_GENDER IN ('F','M'))
);
DROP TABLE DEPT2;
--테이블레벨 제약조건(모든 컬럼 선언 후에 제약조건을 아래에서 추가)
CREATE TABLE DEPT2(
    DEPT_NO NUMBER(2,0),
    DEPT_NAME VARCHAR2(14) NOT NULL,
    LOCA NUMBER(4,0),
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10,0),
    DEPT_GENDER VARCHAR2(1),
    --테이블 레벨 제약 조건
    CONSTRAINT DEPT2_DEPTNO_PK PRIMARY KEY (DEPT_NO),
    CONSTRAINT DEPT2_LOCA_LOC_LOCID_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID),
    CONSTRAINT DEPT2_DEPTBONUS UNIQUE (DEPT_DATE),
    CONSTRAINT DEPT2_DEPTGENDER_CK CHECK (DEPT_GENDER IN ('F','M'))
);
--포린키가 부모테이블에 없다면 불가능
INSERT INTO DEPT2 VALUES(10,'gg',3300,SYSDATE,123123,'F');
--포린키가 부모테이블에 있다면 가능
INSERT INTO DEPT2 VALUES(10,'gg',3000,SYSDATE,123123,'M');
ROLLBACK;
DROP TABLE DEPT2;
--제약조건 추가, 삭제
CREATE TABLE DEPT2(
    DEPT_NO NUMBER(2,0),
    DEPT_NAME VARCHAR2(14) NOT NULL,
    LOCA NUMBER(4,0),
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10,0),
    DEPT_GENDER VARCHAR2(1) CHECK (DEPT_GENDER IN ('F','M'))
);
ALTER TABLE DEPT2 ADD CONSTRAINT DEPT2_DEPTNO_PK PRIMARY KEY (DEPT_NO);--PK추가
ALTER TABLE DEPT2 ADD CONSTRAINT DEPT2_DEPTDATE_UK UNIQUE (DEPT_DATE);--UK추가
ALTER TABLE DEPT2 ADD CONSTRAINT DEPT2_LOCA_LOC_LOCID_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID);--FK추가
DROP TABLE DEPT2;
--제약조건 삭제
ALTER TABLE DEPT2 DROP CONSTRAINT 제약조건명;