--INNER JOIN
SELECT * 
FROM INFO 
INNER JOIN AUTH 
ON INFO.AUTH_ID=AUTH.AUTH_ID;
--AUTH_ID 컬럼을 직접 기술하면, 모호하다 라고 뜨게 됩니다. 그 이유는 양쪽 테이블에 AUTH_ID가 모두 존재하기 때문입니다.
--이럴 때 컬럼에 테이블명.컬럼명을 지정해서 정상적으로 조회할 수 있습니다.
SELECT
    ID,
    TITLE,
    CONTENT,
    REGDATE,
    INFO.AUTH_ID,
    NAME
FROM INFO
INNER JOIN AUTH
ON INFO.AUTH_ID=AUTH.AUTH_ID;
--일반적으로 테이블 앨리어스를 지정해서 사용가능 합니다.
SELECT
    I.ID,
    I.TITLE,
    I.CONTENT,
    I.REGDATE,
    I.AUTH_ID,
    A.NAME
FROM INFO I
INNER JOIN AUTH A
ON I.AUTH_ID=A.AUTH_ID;
--조건절 WHERE구문
SELECT
    ID,
    TITLE,
    CONTENT,
    REGDATE,
    I.AUTH_ID,
    NAME
FROM INFO I
INNER JOIN AUTH A
ON I.AUTH_ID=A.AUTH_ID
WHERE I.AUTH_ID=1;
--아우터 조인
SELECT * 
FROM INFO I
LEFT OUTER JOIN AUTH A
ON I.AUTH_ID=A.AUTH_ID;

SELECT * 
FROM INFO I
RIGHT OUTER JOIN AUTH A
ON I.AUTH_ID=A.AUTH_ID;

SELECT * 
FROM INFO I
FULL OUTER JOIN AUTH A
ON I.AUTH_ID=A.AUTH_ID;

--CROSS JOIN
SELECT * 
FROM INFO I
CROSS JOIN AUTH A;