SELECT ID,TITLE,CONTENT,JOB 
FROM INFO I
JOIN AUTH A
ON I.AUTH_ID=A.AUTH_ID
WHERE JOB='SCIENTIST';

SELECT ID,TITLE,CONTENT,JOB 
FROM INFO I
RIGHT OUTER JOIN AUTH A
ON I.AUTH_ID=A.AUTH_ID
WHERE JOB='SCIENTIST';