--UNION(합집합 중복X),UNION ALL(합집합 중복O),INTERSECT(교집합),MINUS(차집합)
SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'--04년도 입사자
UNION
SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID=20
UNION
SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE JOB_ID='IT_PROG'; 
--주의할점:컬럼개수를 정확히 일치 시켜야 합니다
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME FROM EMPLOYEES WHERE SALARY>=5000
UNION ALL
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID=20
UNION ALL
SELECT 300,'홍','길동' FROM DUAL
UNION ALL
SELECT 400,'김','길자' FROM DUAL;