--형변환 함수 TO_CHAR,TO_DATE,TO_NUMBER
--날짜 -> 문자
SELECT TO_CHAR(SYSDATE) FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH:MI:SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YY-MM-DD PM HH:MI:SS') FROM DUAL;
SELECT TO_CHAR(HIRE_DATE,'YYYY-MM-DD HH:MI:SS') FROM EMPLOYEES;
SELECT TO_CHAR(HIRE_DATE,'YYYY"년"-MM"월"-DD"일"') FROM EMPLOYEES;--특정 문자는 " "로 묶습니다
--숫자 -> 문자
SELECT TO_CHAR(20000,'999999') FROM DUAL;
SELECT TO_CHAR(20000,'99999') FROM DUAL;
SELECT TO_CHAR(20000,'9999') FROM DUAL;--자리수 부족
SELECT TO_CHAR(20000.21,'99999') FROM DUAL;
SELECT TO_CHAR(20000.21,'99999.99') FROM DUAL;--.은 소수점을 나타낸다
SELECT TO_CHAR(20000.21,'99999,99') FROM DUAL;--,는 콤마의 표현 형식
SELECT SALARY FROM EMPLOYEES;
SELECT TO_CHAR(SALARY,'$999,999') AS SALARY FROM EMPLOYEES;
--문자->숫자 TO_NUMBER
SELECT '2000'+2000 FROM DUAL;--자동형변환
SELECT TO_NUMBER('2000')+2000 FROM DUAL;--명시적형변환
SELECT '$3,300'+2000 FROM DUAL;--에러
SELECT TO_NUMBER('$3,300','$9,999')+2000 FROM DUAL;--숫자 FMT를 사용해서 명시적 형변환
--문자->날짜 TO_DATE
SELECT TO_DATE('2020/01/31')+7 FROM DUAL;--날짜형변환
SELECT TO_DATE('2020-01-31')+7 FROM DUAL;--날짜형변환
SELECT TO_DATE('2020-02-03','YY/MM/DD') FROM DUAL;
SELECT TO_DATE('2020-03-03 12:23:03','YY/MM/DD HH:MI:SS') FROM DUAL;--날짜 FMT를 사용해서 명시적 형변환
--NULL제거 NVL, NVL2★
--NXL(컬럼, NULL일 경우 변환할 값)
SELECT NULL FROM DUAL;
SELECT NVL(NULL,0) FROM DUAL;
SELECT FIRST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES;
SELECT FIRST_NAME, SALARY, NVL(COMMISSION_PCT,0) AS COMMISSION_PCT FROM EMPLOYEES;
--NVL2(컬럼, NULL이 아닐 경우 값, NULL일 경우 값)★
SELECT NVL2(NULL,'널이 아닙니다','널입니다') FROM DUAL;
SELECT FIRST_NAME, NVL2(COMMISSION_PCT,'TRUE','FALSE') FROM EMPLOYEES;
SELECT FIRST_NAME, NVL2(COMMISSION_PCT,SALARY+SALARY*COMMISSION_PCT,SALARY) AS 급여 FROM EMPLOYEES;
--DECODE ★ (ELSE IF문)
SELECT DECODE('C','A','A입니다',
                  'B','B입니다',
                  'C','C입니다',
                      '전부아닙니다')
        AS RESULT FROM DUAL;
SELECT FIRST_NAME,JOB_ID,SALARY,DECODE(JOB_ID,'IT_PROG',SALARY*1.1,'FI_MGR',SALARY*1.2,'FI_ACCOUNT',SALARY*1.3,'AD_VP',SALARY*1.4,SALARY) AS RESULT FROM EMPLOYEES;
--CASE WHEN THEN END
SELECT FIRST_NAME,JOB_ID,SALARY,CASE JOB_ID WHEN 'IT_PROG' THEN SALARY*1.1 WHEN 'FI_MGR' THEN SALARY*1.2 WHEN 'FI_ACCOUNT' THEN SALARY*1.3 WHEN 'AD_VP' THEN SALARY*1.4 ELSE SALARY END AS RESULT FROM EMPLOYEES;